appid: "331470"
publishedfileid: "0"
visibility: "0"
title: "Петля времени"
changenote: "Загрузка мода."
previewfile: "deploy/avatar.png"
project_name: "tmlp"
exclusions:
  - ".git"
  - ".github"
  - ".gitattributes"
  - ".gitignore"
  - ".vscode"
  - "scripts"
  - "steamcmd"
  - "build"
  - "README.md"
  - "deploy"
  - "exclusions.yml"
  - "markers.yml"